### ISSUE TITLE
[BUG] Sixth incorrect guess whites out non-matching letters

### ISSUE THREAD

**Issue by ISPOL** [lpatmo/musical-wordle#60]
**Describe the bug**
After six incorrect guesses the last row on the board whites out incorrect letters.

**To Reproduce**
1. Guess six times incorrectly and close the modal.

**Expected behavior**
The last incorrect guess should be handled in the same way as the other guesses.

**Screenshots**
![image](https://user-images.githubusercontent.com/4441258/164949955-17e3df56-b55d-4306-a9af-3160dc14a7f2.png)

**Estimated bug size**
Medium

**Comment by lpatmo** [comment]
@ISPOL I don't see this issue anymore. Can we close this ticket? 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/4512699/229243746-a820666a-4ea7-4b68-86b7-d1b4ab6c1b9a.png">
